<a href="https://colab.research.google.com/github/GaryPython/-Machine-Learning/blob/main/%E7%9B%A3%E7%9D%A3%E5%AD%B8%E7%BF%92/Regularization_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#2.正則化（Regularization）



- 防止過度擬合
- 常與「線性回歸」合併使用
- 損失函數＋懲罰項，提升一般化能力（Generalization Ability）

＊過度擬合＊

”測試“資料誤差 > ”訓練“資料誤差 

機器學習模型太過於複雜，「正則化」可降低模型複雜性

提升模型”一般化“能力

###補充:
[Ridge VS Lasso 回歸](https://kknews.cc/zh-tw/code/leekrqz.html)

In [ ]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures#生成特徵
from sklearn.linear_model import Ridge#脊回歸
from sklearn.metrics import mean_squared_error#平均回歸誤差https://zhuanlan.zhihu.com/p/37663120

#建立data
train_size = 20
test_size = 12
train_X = np.random.uniform(low=0, high=1.2, size=train_size)
test_X = np.random.uniform(low=0.1, high=1.3, size=test_size)
train_y = np.sin(train_X * 2 * np.pi) + np.random.normal(0, 0.2, train_size)
test_y = np.sin(test_X * 2 * np.pi) + np.random.normal(0, 0.2, test_size)
#設定特徵構造
#生成6次方成式
poly = PolynomialFeatures(6) # 次方數
train_poly_X = poly.fit_transform(train_X.reshape(train_size, 1))#分成train_size（20）組，每組1個
test_poly_X = poly.fit_transform(test_X.reshape(test_size, 1))#分成test_size（12）組，每組1個
#正則化-Ridge
model = Ridge(alpha=1.0)
model.fit(train_poly_X, train_y)
train_pred_y = model.predict(train_poly_X)
test_pred_y = model.predict(test_poly_X)
#平均回歸誤差
print(mean_squared_error(train_pred_y, train_y))
print(mean_squared_error(test_pred_y, test_y))

0.16793095778218814
0.32192484002576177


##拆解

In [ ]:
train_X

array([0.75266066, 0.44478805, 0.51856363, 0.47255812, 0.77200116,
       0.6396347 , 1.0519313 , 0.70581185, 0.96655712, 0.48890105,
       1.05309235, 0.46678465, 0.73896734, 0.88795908, 0.06772984,
       0.46074455, 0.49482833, 0.61155026, 0.82364238, 0.88474475])

In [ ]:
train_y

array([-0.75500267,  0.08344515,  0.34639247,  0.33049673, -1.03657418,
       -0.94572124,  0.17592603, -0.9961691 , -0.20713618,  0.26782461,
        0.51484855,  0.18229533, -1.23071075, -0.8248873 ,  0.39323944,
        0.22966223,  0.19742135, -0.59532632, -0.74466451, -0.79319591])

In [ ]:
train_X.reshape(train_size, 1)

array([[0.75266066],
       [0.44478805],
       [0.51856363],
       [0.47255812],
       [0.77200116],
       [0.6396347 ],
       [1.0519313 ],
       [0.70581185],
       [0.96655712],
       [0.48890105],
       [1.05309235],
       [0.46678465],
       [0.73896734],
       [0.88795908],
       [0.06772984],
       [0.46074455],
       [0.49482833],
       [0.61155026],
       [0.82364238],
       [0.88474475]])

In [ ]:
train_poly_X

array([[1.00000000e+00, 7.52660659e-01, 5.66498067e-01, 4.26380808e-01,
        3.20920060e-01, 2.41543904e-01, 1.81800594e-01],
       [1.00000000e+00, 4.44788053e-01, 1.97836412e-01, 8.79952725e-02,
        3.91392459e-02, 1.74086690e-02, 7.74316798e-03],
       [1.00000000e+00, 5.18563625e-01, 2.68908233e-01, 1.39446028e-01,
        7.23116379e-02, 3.74981851e-02, 1.94451948e-02],
       [1.00000000e+00, 4.72558123e-01, 2.23311180e-01, 1.05527512e-01,
        4.98678829e-02, 2.35654732e-02, 1.11360558e-02],
       [1.00000000e+00, 7.72001161e-01, 5.95985792e-01, 4.60101723e-01,
        3.55199064e-01, 2.74214090e-01, 2.11693596e-01],
       [1.00000000e+00, 6.39634701e-01, 4.09132551e-01, 2.61695377e-01,
        1.67389444e-01, 1.07068097e-01, 6.84844701e-02],
       [1.00000000e+00, 1.05193130e+00, 1.10655946e+00, 1.16402454e+00,
        1.22447385e+00, 1.28806237e+00, 1.35495312e+00],
       [1.00000000e+00, 7.05811851e-01, 4.98170369e-01, 3.51614550e-01,
        2.48173716e-01, 1

In [ ]:
train_poly_X[0]

array([1.        , 0.75266066, 0.56649807, 0.42638081, 0.32092006,
       0.2415439 , 0.18180059])

In [ ]:
poly

PolynomialFeatures(degree=2, include_bias=True, interaction_only=False,
                   order='C')

##簡單例子

In [ ]:
import numpy as np
import pandas as pd


###1個變數,6次方,6組數據
#x = [0,1,2,3,4,5]


|<font size=3>x</font> </font><img width=50/>|  <font size=3>x^0</font> </font><img width=50/>  | <font size=3>x^1</font> </font><img width=50/>| <font size=3>x^2</font> </font><img width=50/>      |<font size=3>x^3</font> </font><img width=50/>|<font size=3>x^4</font> </font><img width=50/>|<font size=3>x^5</font> </font><img width=50/>|<font size=3>x^6</font> </font><img width=50/>|
| ---| :---- | :---- | :---- | :---- |:---- |---|---|
|0| 1|0|0|0|0|0|0|
|1| 1|1|1|1|1|1|1|
|2| 1|2|4|8|16|32|64|
|3| 1|3|9|27|81|243|729|
|4| 1|4|16|64|256|1024|4096|
|5| 1|5|25|125|625|3125|15625|

In [ ]:
#6組數據,1個變數
x = np.arange(6).reshape(6,1)
x

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
#6次方數
poly = PolynomialFeatures(6) 
x_poly = poly.fit_transform(x)
x_poly

array([[1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00],
       [1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00],
       [1.0000e+00, 2.0000e+00, 4.0000e+00, 8.0000e+00, 1.6000e+01,
        3.2000e+01, 6.4000e+01],
       [1.0000e+00, 3.0000e+00, 9.0000e+00, 2.7000e+01, 8.1000e+01,
        2.4300e+02, 7.2900e+02],
       [1.0000e+00, 4.0000e+00, 1.6000e+01, 6.4000e+01, 2.5600e+02,
        1.0240e+03, 4.0960e+03],
       [1.0000e+00, 5.0000e+00, 2.5000e+01, 1.2500e+02, 6.2500e+02,
        3.1250e+03, 1.5625e+04]])

In [ ]:
pd.DataFrame(x_poly)

0    1     2      3      4       5        6
0  1.0  0.0   0.0    0.0    0.0     0.0      0.0
1  1.0  1.0   1.0    1.0    1.0     1.0      1.0
2  1.0  2.0   4.0    8.0   16.0    32.0     64.0
3  1.0  3.0   9.0   27.0   81.0   243.0    729.0
4  1.0  4.0  16.0   64.0  256.0  1024.0   4096.0
5  1.0  5.0  25.0  125.0  625.0  3125.0  15625.0

###2個變數,2次方,3組數據
#x = [[0,1],  [2,3],  [4,5]]


|x^0|<font size=3>x</font> </font><img width=50/>|  <font size=3>y</font> </font><img width=50/>|<font size=3>x^2</font> </font><img width=50/>  | <font size=3>x*y</font> </font><img width=50/>| <font size=3>y^2</font> </font><img width=50/>      |
|---| ---| :---- | :---- | :---- | :---- |
|1|0| 1|0|0|1|
|1|2| 3|4|6|9|
|1|4| 5|16|20|25|


In [ ]:
##3組數據,2個變數
x = np.arange(6).reshape(3,2)
x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
poly = PolynomialFeatures(2) # 次方數
x_poly = poly.fit_transform(x)
x_poly

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [ ]:
pd.DataFrame(x_poly)

0    1    2     3     4     5
0  1.0  0.0  1.0   0.0   0.0   1.0
1  1.0  2.0  3.0   4.0   6.0   9.0
2  1.0  4.0  5.0  16.0  20.0  25.0